# Generated by Django 4.2.7 on 2024-03-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=100)),
                ("title_eng", models.CharField(max_length=200)),
                ("prod_year", models.IntegerField()),
                ("runtime", models.IntegerField()),
                ("genre", models.CharField(max_length=30)),
                ("nation", models.CharField(max_length=30)),
                ("director_name", models.CharField(max_length=10)),
                ("director_eng_name", models.CharField(max_length=50)),
                ("actor_name", models.CharField(max_length=100)),
                ("actor_eng_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "movies",
            },
        ),
        migrations.CreateModel(
            name="Poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posterUrl", models.CharField(max_length=200)),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calender.movie"
                    ),
                ),
            ],
            options={
                "db_table": "posters",
            },
        ),
    ]
